/**
 * CRUD operations for Metric View Proposals -- backed by Lakebase (Prisma).
 *
 * Metric views are first-class standalone artifacts: generated by the Genie
 * engine (Phase A) or a standalone API, stored independently, and referenced
 * by Genie spaces and dashboards via deployment validation.
 */

import { withPrisma } from "@/lib/prisma";
import type { MetricViewProposal } from "@/lib/metric-views/types";
import { logger } from "@/lib/logger";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface StoredMetricViewProposal {
  id: string;
  runId: string | null;
  schemaScope: string;
  domain: string | null;
  subdomain: string | null;
  name: string;
  description: string | null;
  yaml: string;
  ddl: string;
  sourceTables: string[];
  hasJoins: boolean;
  classification: string | null;
  rationale: string | null;
  existingFqn: string | null;
  validationStatus: string;
  validationIssues: string[];
  deploymentStatus: string;
  deployedFqn: string | null;
  deployedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

// ---------------------------------------------------------------------------
// Mappers
// ---------------------------------------------------------------------------

function dbRowToStored(row: {
  id: string;
  runId: string | null;
  schemaScope: string;
  domain: string | null;
  subdomain: string | null;
  name: string;
  description: string | null;
  yaml: string;
  ddl: string;
  sourceTablesJson: string | null;
  hasJoins: boolean;
  classification: string | null;
  rationale: string | null;
  existingFqn: string | null;
  validationStatus: string;
  validationIssues: string | null;
  deploymentStatus: string;
  deployedFqn: string | null;
  deployedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}): StoredMetricViewProposal {
  let sourceTables: string[] = [];
  try {
    sourceTables = row.sourceTablesJson ? JSON.parse(row.sourceTablesJson) : [];
  } catch {
    /* empty */
  }

  let validationIssues: string[] = [];
  try {
    validationIssues = row.validationIssues ? JSON.parse(row.validationIssues) : [];
  } catch {
    /* empty */
  }

  return {
    id: row.id,
    runId: row.runId,
    schemaScope: row.schemaScope,
    domain: row.domain,
    subdomain: row.subdomain,
    name: row.name,
    description: row.description,
    yaml: row.yaml,
    ddl: row.ddl,
    sourceTables,
    hasJoins: row.hasJoins,
    classification: row.classification,
    rationale: row.rationale,
    existingFqn: row.existingFqn,
    validationStatus: row.validationStatus,
    validationIssues,
    deploymentStatus: row.deploymentStatus,
    deployedFqn: row.deployedFqn,
    deployedAt: row.deployedAt?.toISOString() ?? null,
    createdAt: row.createdAt.toISOString(),
    updatedAt: row.updatedAt.toISOString(),
  };
}

// ---------------------------------------------------------------------------
// Write
// ---------------------------------------------------------------------------

/**
 * Persist metric view proposals for a run + domain. Replaces existing proposals
 * for the same run + domain combination.
 */
export async function saveMetricViewProposals(
  runId: string | null,
  schemaScope: string,
  domain: string | null,
  proposals: MetricViewProposal[],
): Promise<void> {
  if (proposals.length === 0) return;

  await withPrisma(async (prisma) => {
    await prisma.$transaction(
      async (tx: Parameters<Parameters<typeof prisma.$transaction>[0]>[0]) => {
        // Delete existing proposals for this run + domain
        if (runId && domain) {
          await tx.forgeMetricViewProposal.deleteMany({
            where: { runId, domain },
          });
        } else if (runId) {
          await tx.forgeMetricViewProposal.deleteMany({
            where: { runId, schemaScope },
          });
        }

        const slug = (s: string) =>
          s
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, "_")
            .replace(/^_|_$/g, "");

        await tx.forgeMetricViewProposal.createMany({
          data: proposals.map((p, idx) => ({
            id: runId
              ? `${runId}_mv_${slug(domain ?? schemaScope)}_${idx}`
              : `standalone_mv_${slug(schemaScope)}_${Date.now()}_${idx}`,
            runId,
            schemaScope,
            domain,
            subdomain: p.subdomain ?? null,
            name: p.name,
            description: p.description || null,
            yaml: p.yaml,
            ddl: p.ddl,
            sourceTablesJson: JSON.stringify(p.sourceTables),
            hasJoins: p.hasJoins,
            classification: p.classification ?? null,
            rationale: p.rationale ?? null,
            existingFqn: p.existingFqn ?? null,
            validationStatus: p.validationStatus,
            validationIssues: JSON.stringify(p.validationIssues),
            deploymentStatus: "proposed",
          })),
        });
      },
    );
  });

  logger.info("Metric view proposals saved", {
    runId,
    schemaScope,
    domain,
    count: proposals.length,
  });
}

// ---------------------------------------------------------------------------
// Read
// ---------------------------------------------------------------------------

/** All proposals for a pipeline run. */
export async function getMetricViewProposalsByRun(
  runId: string,
): Promise<StoredMetricViewProposal[]> {
  return withPrisma(async (prisma) => {
    const rows = await prisma.forgeMetricViewProposal.findMany({
      where: { runId },
      orderBy: { createdAt: "asc" },
    });
    return rows.map(dbRowToStored);
  });
}

/** All proposals for a specific run and domain. */
export async function getMetricViewProposalsByRunDomain(
  runId: string,
  domain: string,
): Promise<StoredMetricViewProposal[]> {
  return withPrisma(async (prisma) => {
    const rows = await prisma.forgeMetricViewProposal.findMany({
      where: { runId, domain },
      orderBy: { createdAt: "asc" },
    });
    return rows.map(dbRowToStored);
  });
}

/** All proposals for a schema scope (for standalone use). */
export async function getMetricViewProposalsBySchema(
  schemaScope: string,
): Promise<StoredMetricViewProposal[]> {
  return withPrisma(async (prisma) => {
    const rows = await prisma.forgeMetricViewProposal.findMany({
      where: { schemaScope },
      orderBy: { createdAt: "desc" },
    });
    return rows.map(dbRowToStored);
  });
}

/** Only deployed metric views for a schema scope. */
export async function getDeployedMetricViews(
  schemaScope: string,
): Promise<StoredMetricViewProposal[]> {
  return withPrisma(async (prisma) => {
    const rows = await prisma.forgeMetricViewProposal.findMany({
      where: { schemaScope, deploymentStatus: "deployed" },
      orderBy: { deployedAt: "desc" },
    });
    return rows.map(dbRowToStored);
  });
}

/** Single proposal by ID. */
export async function getMetricViewProposalById(
  id: string,
): Promise<StoredMetricViewProposal | null> {
  return withPrisma(async (prisma) => {
    const row = await prisma.forgeMetricViewProposal.findUnique({
      where: { id },
    });
    return row ? dbRowToStored(row) : null;
  });
}

// ---------------------------------------------------------------------------
// Update
// ---------------------------------------------------------------------------

/** Mark a proposal as deployed, failed, or back to proposed. */
export async function updateDeploymentStatus(
  id: string,
  status: "deployed" | "failed" | "proposed",
  deployedFqn?: string,
): Promise<void> {
  await withPrisma(async (prisma) => {
    await prisma.forgeMetricViewProposal.update({
      where: { id },
      data: {
        deploymentStatus: status,
        deployedFqn: status === "deployed" ? (deployedFqn ?? null) : null,
        deployedAt: status === "deployed" ? new Date() : null,
      },
    });
  });

  logger.info("Metric view deployment status updated", { id, status, deployedFqn });
}

/** Update the YAML and DDL of an existing proposal (e.g. after user edit). */
export async function updateMetricViewProposal(
  id: string,
  data: { yaml?: string; ddl?: string; validationStatus?: string; validationIssues?: string[] },
): Promise<void> {
  await withPrisma(async (prisma) => {
    await prisma.forgeMetricViewProposal.update({
      where: { id },
      data: {
        ...(data.yaml !== undefined && { yaml: data.yaml }),
        ...(data.ddl !== undefined && { ddl: data.ddl }),
        ...(data.validationStatus !== undefined && { validationStatus: data.validationStatus }),
        ...(data.validationIssues !== undefined && {
          validationIssues: JSON.stringify(data.validationIssues),
        }),
      },
    });
  });
}

// ---------------------------------------------------------------------------
// Delete
// ---------------------------------------------------------------------------

/** Delete a single proposal. */
export async function deleteMetricViewProposal(id: string): Promise<void> {
  await withPrisma(async (prisma) => {
    await prisma.forgeMetricViewProposal.delete({ where: { id } });
  });
}

// ---------------------------------------------------------------------------
// Dependency lookup
// ---------------------------------------------------------------------------

/**
 * Find proposals whose name or deployedFqn matches the requested FQNs.
 * Used by deployment dependency validation.
 */
export async function findMetricViewProposalsByFqn(
  fqns: string[],
): Promise<StoredMetricViewProposal[]> {
  if (fqns.length === 0) return [];

  const lowerFqns = fqns.map((f) => f.toLowerCase());

  return withPrisma(async (prisma) => {
    const rows = await prisma.forgeMetricViewProposal.findMany({
      where: {
        OR: [{ deployedFqn: { in: fqns } }, { name: { in: lowerFqns } }],
      },
      orderBy: { createdAt: "desc" },
    });
    return rows.map(dbRowToStored);
  });
}
