// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env.local first (Next.js convention), fall back to .env.
loadEnv({ path: ".env.local" });
loadEnv();

// Atlas Forge — runtime uses pooled URL (DATABASE_URL via @prisma/adapter-pg);
// migrations use the unpooled URL because PgBouncer can't run them.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
