/**
 * POST /api/sql/deploy -- Deploy SQL as notebook, dashboard, or Genie Space.
 *
 * Uses the existing deployment infrastructure:
 *   - Notebook: importNotebook from lib/dbx/workspace.ts
 *   - Dashboard: createDashboard + publishDashboard from lib/dbx/dashboards.ts
 *   - Genie Space: createGenieSpace from lib/dbx/genie.ts
 */

import { NextRequest } from "next/server";
import { importNotebook } from "@/lib/dbx/workspace";
import { logger } from "@/lib/logger";

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const sql = body.sql as string;
    const target = body.target as "notebook" | "dashboard" | "genie";
    const title = (body.title as string) ?? "Forge Assistant Query";
    const path = (body.path as string) ?? "/Shared/forge_assistant/";

    if (!sql || !target) {
      return Response.json(
        { error: "sql and target (notebook|dashboard|genie) are required" },
        { status: 400 },
      );
    }

    if (target === "notebook") {
      const notebookPath = `${path.replace(/\/$/, "")}/${title.replace(/[^a-zA-Z0-9_-]/g, "_")}`;
      const notebookContent = `-- Databricks notebook source\n-- Generated by Forge\n-- ${new Date().toISOString()}\n\n${sql}`;

      await importNotebook({
        path: notebookPath,
        language: "SQL",
        content: notebookContent,
        overwrite: true,
      });

      return Response.json({
        success: true,
        target: "notebook",
        path: notebookPath,
      });
    }

    if (target === "dashboard" || target === "genie") {
      return Response.json(
        {
          error: `${target} deployment from assistant requires additional context. Use the dedicated engines.`,
        },
        { status: 400 },
      );
    }

    return Response.json({ error: "Unknown target" }, { status: 400 });
  } catch (err) {
    logger.error("[api/sql/deploy] Error", { error: String(err) });
    return Response.json(
      { error: err instanceof Error ? err.message : "Failed to deploy" },
      { status: 500 },
    );
  }
}
